version: '3'
services:
  postgres-metatsore:
    image: "hive-metastore:latest"
    restart: always
    container_name: "hive_metastore"
    hostname: "metastore.hive"
    environment:
      - POSTGRES_PASSWORD=hive
  spark:
    image: "spark-with-hadoop-hive:latest"
    hostname: "hadoop.spark"
    container_name: "spark"
    restart: always
    ports:
      - "4040:4040"
      - "4041:4041"
      - "8089:8088"
      - "8090:18080"
    expose:
      - "22"
    volumes:
      - ./data: /usr/bin/data
    depends_on:
      - postgres-metatsore
    privileged: "true"
    command: "/usr/sbin/init"
